# Generated by Django 5.2.14 on 2026-05-21 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='seat_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum registration seats. Use 0 for no fixed limit.'),
        ),
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_rows', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cse_icb_event_feedback',
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='uniq_cse_icb_feedback_event_user'), models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='chk_cse_icb_feedback_rating_1_5')],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_rows', to='events.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='events.student')),
            ],
            options={
                'db_table': 'cse_icb_event_registrations',
                'ordering': ['-registered_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'student'), name='uniq_cse_icb_registration_event_student')],
            },
        ),
    ]
