# Generated by Django 5.2.14 on 2026-05-22 01:23

import django.db.models.deletion
import events.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_seat_limit_eventfeedback_eventregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], max_length=32)),
                ('file_path', models.FileField(upload_to=events.models.event_media_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_rows', to='events.event')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_event_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cse_icb_event_media',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
